## argocd role

- name: "{{ argocd.helm.name | upper }}| Adding Helm Repo {{ argocd.helm.repository_url }}"
  community.kubernetes.helm_repository:
    name: "{{ argocd.helm.name }}"
    repo_url: "{{ argocd.helm.repository_url }}"

- name: "{{ argocd.helm.name | upper }} | Deploy latest version of {{argocd.helm.chart_ref }} chart inside {{argocd.helm.namespace }} namespace"
  community.kubernetes.helm:
    name: "{{ argocd.helm.name }}"
    chart_ref: "{{ argocd.helm.chart_ref }}"
    release_namespace: "{{ argocd.helm.namespace }}"
    create_namespace: "yes"
      ---
